In [4]:
import torch

x = torch.arange(12)
print(x)
print(x.shape)
print(x.numel())

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12


In [7]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1,2))
print(a)
print(b)
print(a + b)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1]])
tensor([[0, 1],
        [1, 2],
        [2, 3]])


In [16]:
a2 = torch.tensor([
    [0],
    [1],
    [2]])
b2 = torch.tensor([[0, 1, 2]])
print(a2)
print(b2)
print(a2 + b2)

tensor([[0],
        [1],
        [2]])
tensor([[0, 1, 2]])
tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]])


In [1]:
import os
import pandas

root = os.path.join(os.getcwd(),'data')
os.makedirs(root, exist_ok=True)
# os.mkdir(root)
print(root)

/Users/zhouxinyu/Code/Python/jupyter/PyTorch/d2l-zh/practice/data
