In [1]:
import numpy as np
import xlrd

In [2]:
arr = np.array([
        [
            [1, 2, 3],
            [2, 4, 4]
    ]
])

In [3]:
arr.shape

(1, 2, 3)

In [1]:
import xlrd
from numpy import random, dot, exp, array
import numpy as np
import pandas as pd

In [21]:
# Min-Max标准化
# 参考链接：https://www.icode9.com/content-4-613783.html
def maxminnorm(array):
    global maxcols, mincols
    data_shape = array.shape
    data_rows = data_shape[0] # 行数
    data_cols = data_shape[1] # 列数
    maxcols = array.max(axis=1).reshape(data_rows, 1) # 每一行的最大值
    mincols = array.min(axis=1).reshape(data_rows, 1) # 每一行的最小值
    t = np.empty((data_rows, data_cols)) # 和原矩阵行列数相同的空矩阵
    for i in range(data_rows):
        t[i, :] = (array[i, :]-mincols[i])/(maxcols[i]-mincols[i])
    return t

In [ ]:
# 没看明白和maxminnorm除了变量名还有什么区别
def maxminnorm2(array):
    global maxcols2, mincols2
    data_shape = array.shape
    data_rows = data_shape[0]
    data_cols = data_shape[1]
    maxcols2 = array.max(axis=1).reshape(data_rows, 1)
    mincols2 = array.min(axis=1).reshape(data_rows, 1)
    t = np.empty((data_rows, data_cols))
    for i in range(data_rows):
        t[i, :] = (array[i, :]-mincols2[i])/(maxcols2[i]-mincols2[i])
    return t

In [30]:

testArr.min(axis=1).reshape(3, 1)

array([[ 1],
       [11],
       [11]])

In [38]:
testArrTest = np.array([1, 2, 3])
print(testArrTest + testArrTest)

[2 4 6]


In [7]:
def remaxminnorm(array):
    data_shape = array.shape
    data_rows = data_shape[0] # 行数
    data_cols = data_shape[1] # 列数
    t = np.empty((data_rows, data_cols)) # 和原矩阵行列数相同的空矩阵
    for i in range(data_rows):
        # 新矩阵的第i行 = 原矩阵的第i行 * (原矩阵第i行最大值 - 原矩阵第i行最小值) + 原矩阵的第i行【这里的相加是对应位置相加】
        t[i, :] = ((array[i, :])*(maxcols2[i]-mincols2[i])+mincols2[i])
    return t

In [8]:
# 好像和maxminnorm一样
def usemaxminnorm(array):
    data_shape = array.shape
    data_rows = data_shape[0]
    data_cols = data_shape[1]
    t = np.empty((data_rows, data_cols))
    for i in range(data_rows):
        t[i, :] = ((array[i, :]-mincols[i])/(maxcols[i]-mincols[i]))
    return t

In [5]:
# 数据处理
table = xlrd.open_workbook(r"/Users/zhouxinyu/Code/jz/data.xls", 'rb')

In [12]:
sheet1 = table.sheet_names()[0]
print("sheet1 -> ", sheet1)
sheet1 = table.sheet_by_index(0)
print("sheet1 2 -> ", sheet1)

rowNum = sheet1.nrows
colNum = sheet1.ncols

print("rowNum -> ", rowNum)
print("colNum -> ", colNum)

newlist = []

for i in range(rowNum):
    rowi = sheet1.row_values(i)
    print("rowi[2:] --> ", rowi[2:])
    newlist.append(rowi[2:])

sheet1 ->  Sheet1
sheet1 2 ->  Sheet  0:<Sheet1>
rowNum ->  11
colNum ->  23
rowi[2:] -->  ['', 2021.0, '', '', 2020.0, '', '', '', 2019.0, '', '', '', 2018.0, '', '', '', 2017.0, '', '', '', 2016.0]
rowi[2:] -->  [0.0, 17.57, 17.66, 26.56, 28.5, 27.87, 28.27, 19.24, 17.39, 16.64, 17.74, 19.01, 20.88, 18.16, 19.45, 32.2, 30.89, 35.21, 35.66, 34.0, 31.11]
rowi[2:] -->  [72.44, 72.44, 43.0, 17.6, 83.53, 50.94, 25.55, 7.63, 76.86, 53.12, 31.42, 11.85, 73.11, 51.06, 29.88, 12.43, 61.61, 42.51, 24.87, 9.54, 45.3]
rowi[2:] -->  [8.77, 8.77, 4.55, 1.15, 12.24, 7.15, 3.47, -0.27, 10.95, 7.29, 3.89, 0.96, 9.64, 6.87, 3.59, 0.86, 9.05, 5.71, 2.87, 0.66, 6.37]
rowi[2:] -->  [6.96, 6.96, 6.62, 6.86, 6.71, 6.14, 5.78, 5.95, 5.97, 5.57, 5.14, 4.85, 5.23, 5.13, 4.79, 4.95, 4.84, 4.48, 4.18, 8.59, 8.42]
rowi[2:] -->  [8.91, 8.91, 8.75, 8.23, 8.4, 4.66, 5.17, 5.84, 6.94, 5.48, 5.23, 4.62, 4.07, 4.29, 4.06, 2.9, 2.24, 1.8, 1.35, 1.18, 1.2]
rowi[2:] -->  [7.23, 7.23, 6.61, 5.48, 4.93, 6.09, 5.27, 3.99, 3

In [17]:
# 引入数据
# 定义一个数组，数组的第一个元素是newlist[2][3:]，第二个元素是newlist[2][3:]，第三个元素是newlist[4][3:]，以此类推
# newlist[2][3:]代表，newlist[2][3]-newlist[2][max]的全部元素，是一个一位数组
gjys = array([newlist[2][3:],newlist[2][3:],newlist[4][3:],newlist[5][3:],newlist[6][3:],newlist[7][3:]])
# T转置：表示整个顺序颠倒
gjys = maxminnorm(gjys).T

In [46]:
testArr = np.array(
    [
        [1, 2, 3],
        [11, 12, 13],
        [11, 21, 31],
    ]
)
testArr[1][1:]

array([12, 13])

In [40]:

print("gjys -> ", gjys)
print("maxminnorm(gjys) -> ", maxminnorm(gjys))
print("maxminnorm(gjys).T -> ", maxminnorm(gjys).T)
# gj = array(newlist[1][3:]).reshape(1,18)

gjys ->  [[2.01331542e-02 1.00000000e+00 2.27114625e-01 0.00000000e+00
  0.00000000e+00 1.00000000e+00 9.85758753e-01 3.80419372e-01
  0.00000000e+00 1.00000000e+00 1.00000000e+00 7.27390367e-01
  2.65465576e-01 9.54624336e-01 9.61370576e-01 9.04947005e-01
  2.51646904e-02 5.14812297e-01]
 [0.00000000e+00 1.00000000e+00 2.67625899e-01 1.18246950e-01
  0.00000000e+00 9.77490607e-01 1.00000000e+00 4.28220954e-01
  1.01512132e-01 9.03302127e-01 9.96734968e-01 7.67103170e-01
  3.79166434e-01 1.00000000e+00 1.00000000e+00 1.00000000e+00
  7.43405276e-02 5.50762147e-01]
 [5.57479619e-01 0.00000000e+00 0.00000000e+00 2.38356674e-01
  6.21850457e-01 2.52244895e-01 1.72416425e-01 1.40721867e-01
  2.28886447e-01 1.43852977e-01 2.00402170e-01 3.28240867e-01
  7.32927279e-01 2.00884646e-01 1.42311105e-01 0.00000000e+00
  1.00000000e+00 1.00000000e+00]
 [9.73439424e-01 1.00000000e+00 6.75900277e-02 5.95425735e-01
  1.00000000e+00 8.31110285e-01 9.74957912e-01 1.00000000e+00
  1.00000000e+00 3.66150